In [ ]:
##Website phishing Detection

##Phishing problem:
Problem Statement: Phishing Website Detection using Machine Learning

In the digital age, online security has become a major concern as users increasingly rely on the internet for financial transactions, communication, and information exchange. Phishing attacks are one of the most common and dangerous forms of cybercrime, where attackers create fraudulent websites that mimic legitimate ones to steal sensitive information such as usernames, passwords, and credit card details.

Traditional methods of detecting phishing websites such as maintaining blacklists or using rule based filters are often ineffective against newly created or rapidly changing phishing sites. These methods require frequent manual updates and fail to generalize well to novel attacks.

This project aims to develop a machine learning based phishing website detection model that can automatically identify whether a given website is legitimate or phishing based on its URL structure, domain features, and webpage characteristics. By learning from patterns in historical data, the model should be able to generalize to unseen websites and make real-time predictions.

## Baseline Model
In base line model - 1. splitting data All features (X) as input features everthing that model use to predict
(Y) feature - output varibale (what you want model to predict)
2. Use 70% of the data for traning and remaning 30% to testing...
3. Then, looked for models who needs scalling for better output and set the scalling on split data x_train and x_test.
4. After that, applied models Logistic Regression, KNN, SVM, Random forest, Decision Tree. For all these model predicted the accuracy for training as well as test data. And plot all traning and tested accuracy on the figure.

##Variables - Input - Output = Description

In [ ]:
import pandas as pd  # For data handling and processing
import numpy as np
# model evaluation related packages
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Logistic Regression modeling package(s) (sklearn)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# # Example: pick a C value
# #model_log_reg = LogisticRegression(C=1, solver='liblinear', max_iter=1000)

# # Train the model
# model_log_reg.fit(X_train_scaled, y_train)

# # Generate predictions
# y_train_pred = model_log_reg.predict(X_train_scaled)  # <-- now y_train_pred is defined

# # Check predictions
# print(y_train_pred)
# print("Train Accuracy:", accuracy_score(y_train, y_train_pred))

#applying ml models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# visualization
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:

#data_path = '/content/drive/MyDrive/Colab Notebooks/phishing.csv'

In [ ]:
data = pd.read_csv('/content/phishing.csv')

In [ ]:
#checking data need scaling or not for model application
# data.describe().T

In [ ]:
#lists of colum names
data.columns

Index(['Index', 'UsingIP', 'LongURL', 'ShortURL', 'Symbol@', 'Redirecting//',
       'PrefixSuffix-', 'SubDomains', 'HTTPS', 'DomainRegLen', 'Favicon',
       'NonStdPort', 'HTTPSDomainURL', 'RequestURL', 'AnchorURL',
       'LinksInScriptTags', 'ServerFormHandler', 'InfoEmail', 'AbnormalURL',
       'WebsiteForwarding', 'StatusBarCust', 'DisableRightClick',
       'UsingPopupWindow', 'IframeRedirection', 'AgeofDomain', 'DNSRecording',
       'WebsiteTraffic', 'PageRank', 'GoogleIndex', 'LinksPointingToPage',
       'StatsReport', 'class'],
      dtype='object')

In [ ]:
#see variables and its values
data.head()

,Index,UsingIP,LongURL,ShortURL,Symbol@,Redirecting//,PrefixSuffix-,SubDomains,HTTPS,DomainRegLen,...,UsingPopupWindow,IframeRedirection,AgeofDomain,DNSRecording,WebsiteTraffic,PageRank,GoogleIndex,LinksPointingToPage,StatsReport,class
0,0,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
1,1,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
2,2,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
3,3,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1
4,4,-1,0,-1,1,-1,-1,1,1,-1,...,1,1,1,1,1,-1,1,-1,-1,1

In [ ]:
data.describe()

,Index,UsingIP,LongURL,ShortURL,Symbol@,Redirecting//,PrefixSuffix-,SubDomains,HTTPS,DomainRegLen,...,UsingPopupWindow,IframeRedirection,AgeofDomain,DNSRecording,WebsiteTraffic,PageRank,GoogleIndex,LinksPointingToPage,StatsReport,class
count,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,...,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000,11054.000000
mean,5526.500000,0.313914,-0.633345,0.738737,0.700561,0.741632,-0.734938,0.064049,0.251040,-0.336711,...,0.613353,0.816899,0.061335,0.377239,0.287407,-0.483626,0.721549,0.343948,0.719739,0.113986
std,3191.159272,0.949495,0.765973,0.674024,0.713625,0.670837,0.678165,0.817492,0.911856,0.941651,...,0.789845,0.576807,0.998162,0.926158,0.827680,0.875314,0.692395,0.569936,0.694276,0.993527
min,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,2763.250000,-1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,1.000000,1.000000,-1.000000,-1.000000,0.000000,-1.000000,1.000000,0.000000,1.000000,-1.000000
50%,5526.500000,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,1.000000,-1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,0.000000,1.000000,1.000000
75%,8289.750000,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,11053.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
#splitting the input and output features
X = data.iloc[:,:-1] #all features
Y = data.iloc[:,-1] # y

#spliting the test and train data
# test data amount (in terms of proportion)
TEST_PROP = 0.3
# Random number seed; important for experiment reproducibility
RANDOM_SEED = 42 #42 ensures same split all the time

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=TEST_PROP, random_state=RANDOM_SEED)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((7737, 31), (7737,), (3317, 31), (3317,))

In [ ]:
#for mordels that need scaling
feature_scaler = StandardScaler()
X_train_scaled = feature_scaler.fit_transform(X_train)
X_test_scaled = feature_scaler.transform(X_test)

In [ ]:
#Applying logistical Regression
model_log_reg = LogisticRegression(max_iter=1000)
model_log_reg.fit(X_train_scaled, y_train) #Logictical regressions need scaling

model_log_reg_pred_train = model_log_reg.predict(X_train_scaled) #train
model_log_reg_pred_test = model_log_reg.predict(X_test_scaled) #test

# Estimating the accuracy for training data
acc_train_log_reg = accuracy_score(y_train, model_log_reg_pred_train)
print("accuracy score (training data): %.2f" % acc_train_log_reg)

# Estimating the accuracy for test data
acc_test_log_reg = accuracy_score(y_test, model_log_reg_pred_test)
print("accuracy score (test data): %.2f" % acc_test_log_reg)

#for showing accuracy,
lreg_results = pd.DataFrame({
  'model': ['lr'],
  'train_acc': [acc_train_log_reg],
  'test_acc': [acc_test_log_reg]
})

accuracy score (training data): 0.93
accuracy score (test data): 0.93

##Checking the performace of unoptimizerd modles for further improvments: using trainign and test accuracy, confusion metrix and classification report, and interpretations:

In [ ]:
#Logistic Regression model
print("Accuracy (training data): %.2f" % acc_train_log_reg)
print(f"\nConfusion Matrix (Train Data):", confusion_matrix(y_train, model_log_reg_pred_train))
print(f"\nClassification Report (Train Data):", classification_report(y_train, model_log_reg_pred_train))

#
print("Accuracy (test data): %.2f" % acc_test_log_reg)
print(f"\nConfusion Matrix (Test Data):", confusion_matrix(y_test, model_log_reg_pred_test))
print(f"\nClassification Report (Test Data):", classification_report(y_test, model_log_reg_pred_test))

Accuracy (training data): 0.93

Confusion Matrix (Train Data): [[3132  310]
 [ 240 4055]]

Classification Report (Train Data):               precision    recall  f1-score   support

          -1       0.93      0.91      0.92      3442
           1       0.93      0.94      0.94      4295

    accuracy                           0.93      7737
   macro avg       0.93      0.93      0.93      7737
weighted avg       0.93      0.93      0.93      7737

Accuracy (test data): 0.93

Confusion Matrix (Test Data): [[1307  148]
 [  95 1767]]

Classification Report (Test Data):               precision    recall  f1-score   support

          -1       0.93      0.90      0.91      1455
           1       0.92      0.95      0.94      1862

    accuracy                           0.93      3317
   macro avg       0.93      0.92      0.93      3317
weighted avg       0.93      0.93      0.93      3317

##The model achieves an overall accuracy of 93% on both training and test sets, indicating good generalization. The confusion matrices show the model correctly predicts the majority of both positive and negative cases, with slightly more misclassifications in the negative class. Precision, recall, and F1-scores are all above 0.90 for both classes, confirming that the model maintains strong performance across all key metrics.

In [ ]:
# Applying KNN model
N_NEAREST_NEIGHOR_PARAM = 10
model_knn = KNeighborsClassifier(n_neighbors=N_NEAREST_NEIGHOR_PARAM)
model_knn.fit(X_train_scaled, y_train)

#model_knn = KNeighborsClassifier() #just like LG, KNN needs scalling too so applying scalling vari
#model_knn.fit(X_train_scaled, y_train)
model_knn_pred_train = model_knn.predict(X_train_scaled) #for traning
model_knn_pred_test = model_knn.predict(X_test_scaled) #for testing


# Estimating the accuracy for training data
acc_train_knn = accuracy_score(y_train, model_knn_pred_train)
print("accuracy score (training data): %.2f" % acc_train_knn)

# Estimating the accuracy for test data
acc_test_knn = accuracy_score(y_test, model_knn_pred_test)
print("accuracy score (test data): %.2f" % acc_test_knn)

#for showing accuracy,
knn_results = pd.DataFrame({
  'model': ['lr'],
  'train_acc': [acc_train_knn],
  'test_acc': [acc_test_knn]
})

accuracy score (training data): 0.95
accuracy score (test data): 0.93

In [ ]:
#for knn model
print("Accuracy (training data): %.2f" % acc_train_knn)
print(f"\nConfusion Matrix (Train Data):", confusion_matrix(y_train, model_knn_pred_train))
print(f"\nClassification Report (Train Data):", classification_report(y_train, model_knn_pred_train))

print("Accuracy (test data): %.2f" % acc_test_knn)
print(f"\nConfusion Matrix (Test Data):", confusion_matrix(y_test, model_knn_pred_test))
print(f"\nClassification Report (Test Data):", classification_report(y_test, model_knn_pred_test))

Accuracy (training data): 0.95

Confusion Matrix (Train Data): [[3297  145]
 [ 252 4043]]

Classification Report (Train Data):               precision    recall  f1-score   support

          -1       0.93      0.96      0.94      3442
           1       0.97      0.94      0.95      4295

    accuracy                           0.95      7737
   macro avg       0.95      0.95      0.95      7737
weighted avg       0.95      0.95      0.95      7737

Accuracy (test data): 0.93

Confusion Matrix (Test Data): [[1364   91]
 [ 135 1727]]

Classification Report (Test Data):               precision    recall  f1-score   support

          -1       0.91      0.94      0.92      1455
           1       0.95      0.93      0.94      1862

    accuracy                           0.93      3317
   macro avg       0.93      0.93      0.93      3317
weighted avg       0.93      0.93      0.93      3317

The model achieves 95% accuracy on training data and 93% on test data, demonstrating strong generalization. Confusion matrices show correct predictions for the majority of both negative and positive classes, with slightly higher recall for class -1 and higher precision for class 1. Overall, precision, recall, and F1-scores above 0.90 indicate balanced and reliable performance across both classes.

In [ ]:
# #Applying SVM (Support Vector Machine) Model
model_svm = SVC()
model_svm.fit(X_train_scaled, y_train)
model_svm_pred_train = model_svm.predict(X_train_scaled) #for Training
model_svm_pred_test = model_svm.predict(X_test_scaled) #for testing  # FIXED: was model_knn.predict(), now correctly uses model_svm


# Estimating the accuracy for training data
acc_train_svm = accuracy_score(y_train, model_svm_pred_train)
print("accuracy score (training data): %.2f" % acc_train_svm)

# Estimating the accuracy for test data
acc_test_svm = accuracy_score(y_test, model_svm_pred_test)
print("accuracy score (test data): %.2f" % acc_test_svm)

#for showing accuracy,
svm_results = pd.DataFrame({
  'model': ['svm'],
  'train_acc': [acc_train_svm],
  'test_acc': [acc_test_svm]
})

In [ ]:
#for SVM model

print("Accuracy (training data): %.2f" % acc_train_svm)
print(f"\nConfusion Matrix (Train Data):", confusion_matrix(y_train, model_svm_pred_train))
print(f"\nClassification Report (Train Data):",classification_report(y_train, model_svm_pred_train))


print("Accuracy (test data): %.2f" % acc_test_svm)
print("\nConfusion Matrix (Test Data):", confusion_matrix(y_test, model_svm_pred_test))
print("\nClassification Report (Test Data):", classification_report(y_test, model_svm_pred_test))

Accuracy (training data): 0.96

Confusion Matrix (Train Data): [[3251  191]
 [ 129 4166]]

Classification Report (Train Data):               precision    recall  f1-score   support

          -1       0.96      0.94      0.95      3442
           1       0.96      0.97      0.96      4295

    accuracy                           0.96      7737
   macro avg       0.96      0.96      0.96      7737
weighted avg       0.96      0.96      0.96      7737

Accuracy (test data): 0.93

Confusion Matrix (Test Data): [[1364   91]
 [ 135 1727]]

Classification Report (Test Data):               precision    recall  f1-score   support

          -1       0.91      0.94      0.92      1455
           1       0.95      0.93      0.94      1862

    accuracy                           0.93      3317
   macro avg       0.93      0.93      0.93      3317
weighted avg       0.93      0.93      0.93      3317

The SVM model achieves 96% accuracy on training data and 93% on test data, indicating strong generalization. Confusion matrices show the model correctly predicts the majority of both negative and positive classes. Precision, recall, and F1-scores above 0.90 for both classes indicate balanced and reliable performance, with minor differences between train and test metrics that are expected in real-world data.

In [ ]:
# Applying Random Forest Model
model_rf = RandomForestClassifier(
    n_estimators=100, max_depth=2, random_state=42
)
model_rf.fit(X_train, y_train)


model_rf_pred_train = model_rf.predict(X_train)#for traning data
model_rf_pred_test = model_rf.predict(X_test) #for testing

# Estimating the accuracy for training data
acc_train_rf = accuracy_score(y_train, model_rf_pred_train)
print("accuracy score (training data): %.2f" % acc_train_rf)

# Estimating the accuracy for test data
acc_test_rf = accuracy_score(y_test, model_rf_pred_test)
print("accuracy score (test data): %.2f" % acc_test_rf)

#for showing accuracy,
rf_results = pd.DataFrame({
  'model': ['lr'],
  'train_acc': [acc_train_rf],
  'test_acc': [acc_test_rf]
})

accuracy score (training data): 0.92
accuracy score (test data): 0.92

In [ ]:
# for Random Forest
print("Accuracy (training data): %.2f" % acc_train_rf)
print(f"\nConfusion Matrix (Train Data):", confusion_matrix(y_train, model_rf_pred_train))
print(f"\nClassification Report (Train Data):", classification_report(y_train, model_rf_pred_train))

print("Accuracy (test data): %.2f" % acc_test_rf)
print("\nConfusion Matrix (Test Data):", confusion_matrix(y_test, model_rf_pred_test))
print(f"\nClassification Report (Test Data):", classification_report(y_test, model_rf_pred_test))

Accuracy (training data): 0.92

Confusion Matrix (Train Data): [[2943  499]
 [ 127 4168]]

Classification Report (Train Data):               precision    recall  f1-score   support

          -1       0.96      0.86      0.90      3442
           1       0.89      0.97      0.93      4295

    accuracy                           0.92      7737
   macro avg       0.93      0.91      0.92      7737
weighted avg       0.92      0.92      0.92      7737

Accuracy (test data): 0.92

Confusion Matrix (Test Data): [[1247  208]
 [  58 1804]]

Classification Report (Test Data):               precision    recall  f1-score   support

          -1       0.96      0.86      0.90      1455
           1       0.90      0.97      0.93      1862

    accuracy                           0.92      3317
   macro avg       0.93      0.91      0.92      3317
weighted avg       0.92      0.92      0.92      3317

The Random Forest model achieves 92% accuracy on both training and test data, indicating strong generalization. Confusion matrices show that the model predicts positive cases (1) very accurately, while some negative cases (-1) are misclassified. Precision, recall, and F1-scores above 0.90 for both classes indicate balanced and reliable performance, with a minor bias toward better identification of the positive class.

In [ ]:
# #Decision Tree
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)
model_dt_pred_train = model_dt.predict(X_train)
model_dt_pred_test = model_dt.predict(X_test)



# Estimating the accuracy for training data
acc_train_dt = accuracy_score(y_train, model_dt_pred_train)
print("accuracy score (training data): %.2f" % acc_train_dt)

# Estimating the accuracy for test data
acc_test_dt = accuracy_score(y_test, model_dt_pred_test)
print("accuracy score (test data): %.2f" % acc_test_dt)



#for showing accuracy,
dt_results = pd.DataFrame({
  'model': ['lr'],
  'train_acc': [acc_train_dt],
  'test_acc': [acc_test_dt]
})

accuracy score (training data): 1.00
accuracy score (test data): 0.95

In [ ]:
#for  Decision Tree
print("Accuracy (training data): %.2f" % acc_train_dt)
print(f"\nConfusion Matrix (Train Data):", confusion_matrix(y_train, model_dt_pred_train))
print(f"\nClassification Report (Train Data):", classification_report(y_train, model_dt_pred_train))

print("Accuracy (test data): %.2f" % acc_test_dt)
print(f"\nConfusion Matrix (Test Data):", confusion_matrix(y_test, model_dt_pred_test))
print(f"\nClassification Report (Test Data):", classification_report(y_test, model_dt_pred_test))

Accuracy (training data): 1.00

Confusion Matrix (Train Data): [[3442    0]
 [   0 4295]]

Classification Report (Train Data):               precision    recall  f1-score   support

          -1       1.00      1.00      1.00      3442
           1       1.00      1.00      1.00      4295

    accuracy                           1.00      7737
   macro avg       1.00      1.00      1.00      7737
weighted avg       1.00      1.00      1.00      7737

Accuracy (test data): 0.95

Confusion Matrix (Test Data): [[1366   89]
 [  85 1777]]

Classification Report (Test Data):               precision    recall  f1-score   support

          -1       0.94      0.94      0.94      1455
           1       0.95      0.95      0.95      1862

    accuracy                           0.95      3317
   macro avg       0.95      0.95      0.95      3317
weighted avg       0.95      0.95      0.95      3317

In [ ]:
from sklearn.metrics import f1_score

# Comparison table computed directly from actual model predictions (not hardcoded)
model_preds = {
    'Logistic Regression': (model_log_reg_pred_train, model_log_reg_pred_test),
    'KNN': (model_knn_pred_train, model_knn_pred_test),
    'SVM': (model_svm_pred_train, model_svm_pred_test),
    'Random Forest': (model_rf_pred_train, model_rf_pred_test),
    'Decision Tree': (model_dt_pred_train, model_dt_pred_test),
}

rows = []
for name, (pred_train, pred_test) in model_preds.items():
    rows.append({
        'Model': name,
        'Train Accuracy': accuracy_score(y_train, pred_train),
        'Test Accuracy': accuracy_score(y_test, pred_test),
        'Train F1 (-1)': f1_score(y_train, pred_train, pos_label=-1),
        'Train F1 (1)': f1_score(y_train, pred_train, pos_label=1),
        'Test F1 (-1)': f1_score(y_test, pred_test, pos_label=-1),
        'Test F1 (1)': f1_score(y_test, pred_test, pos_label=1),
    })

df_results = pd.DataFrame(rows)
print(df_results)

Explanation:
Train Accuracy and Test Accuracy show overall correctness on training and test data.
'Train F1 (-1)' and 'Train F1 (1)' show the F1-score for the negative and positive classes in training.
'Test F1 (-1)' and 'Test F1 (1)' show the F1-score for the negative and positive classes in testing.
SVM: High F1-scores, balanced performance, slight difference between train/test.
Random Forest: Strong generalization, slightly better on positive class.
Decision Tree: Perfect training accuracy (overfitting tendency), still high test F1 (0.94-0.95), very reliable predictions.
"""

In [ ]:
#All the model i used listed here:
lreg_results['model'] = 'Logistic Regression'  # FIXED: was mislabeled 'Linear Regression'
knn_results['model']  = 'KNN'
rf_results['model']   = 'Random Forest'
svm_results['model']  = 'SVM'
dt_results['model']   = 'Decision Tree'

results = pd.concat([lreg_results, knn_results, rf_results, svm_results, dt_results], axis=0)


fig = go.Figure([
    go.Bar(x=results.model, y=results.train_acc, name='Training Accuracy'),
    go.Bar(x=results.model, y=results.test_acc, name='Test Accuracy')
])

# Update layout for titles and grouping
fig.update_layout(
    title="Model Comparison",
    xaxis_title="Model",
    yaxis_title="Accuracy",
    barmode='group',  # groups bars side by side
    legend=dict(
        x=0.05,
        y=0.95
    )
)

fig.show()

##Stage 2

Want to try model tuning for better efficiency, then cross validation for further evaluation of the model

This loop iterates over a list of values for the hyperparameter C.
C is the inverse of the regularization strength in Logistic Regression.
Smaller values mean stronger regularization (more penalty on complexity).
Larger values mean weaker regularization.
Creates a Logistic Regression model for the current C value.
solver='liblinear' is an algorithm choice suitable for small datasets and binary classification.
max_iter=1000 allows up to 1000 iterations for convergence, ensuring the model can fully train.

In [ ]:
#Tuned Logistic Regression (with real cross-validation via GridSearchCV)
from sklearn.model_selection import GridSearchCV

param_grid_lr = {'C': [0.01, 0.1, 1, 10]}
grid_lr = GridSearchCV(
    LogisticRegression(max_iter=1000, solver='liblinear'),
    param_grid_lr, cv=5, scoring='accuracy'
)
grid_lr.fit(X_train_scaled, y_train)

print("Best C:", grid_lr.best_params_)
print("Best CV accuracy:", grid_lr.best_score_)

best_lr = grid_lr.best_estimator_
y_lr_train_pred = best_lr.predict(X_train_scaled)
y_lr_test_pred = best_lr.predict(X_test_scaled)

acc_train_lr_tuned = accuracy_score(y_train, y_lr_train_pred)
acc_test_lr_tuned = accuracy_score(y_test, y_lr_test_pred)
print(f"Tuned LR - Train Acc: {acc_train_lr_tuned:.2f}, Test Acc: {acc_test_lr_tuned:.2f}")

print("\nConfusion Matrix (Test):", confusion_matrix(y_test, y_lr_test_pred))
print("\nClassification Report (Test):", classification_report(y_test, y_lr_test_pred))

In [ ]:
#tuned knn model (with real cross-validation via GridSearchCV)
param_grid_knn = {'n_neighbors': [3, 5, 7, 10, 15], 'weights': ['uniform', 'distance']}
grid_knn = GridSearchCV(KNeighborsClassifier(), param_grid_knn, cv=5, scoring='accuracy')
grid_knn.fit(X_train_scaled, y_train)

print("Best params:", grid_knn.best_params_)
print("Best CV accuracy:", grid_knn.best_score_)

best_knn = grid_knn.best_estimator_
y_knn_train_pred = best_knn.predict(X_train_scaled)
y_knn_test_pred = best_knn.predict(X_test_scaled)

acc_train_knn_tuned = accuracy_score(y_train, y_knn_train_pred)
acc_test_knn_tuned = accuracy_score(y_test, y_knn_test_pred)
print(f"Tuned KNN - Train Acc: {acc_train_knn_tuned:.2f}, Test Acc: {acc_test_knn_tuned:.2f}")

print("\nConfusion Matrix (Test):", confusion_matrix(y_test, y_knn_test_pred))
print("\nClassification Report (Test):", classification_report(y_test, y_knn_test_pred))

In [ ]:
# Tuned SVM model (with real cross-validation via GridSearchCV)
param_grid_svm = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf']}
grid_svm = GridSearchCV(SVC(gamma='scale'), param_grid_svm, cv=5, scoring='accuracy')
grid_svm.fit(X_train_scaled, y_train)

print("Best params:", grid_svm.best_params_)
print("Best CV accuracy:", grid_svm.best_score_)

best_svm = grid_svm.best_estimator_
y_svm_train_pred = best_svm.predict(X_train_scaled)
y_svm_test_pred = best_svm.predict(X_test_scaled)

acc_train_svm_tuned = accuracy_score(y_train, y_svm_train_pred)
acc_test_svm_tuned = accuracy_score(y_test, y_svm_test_pred)
print(f"Tuned SVM - Train Acc: {acc_train_svm_tuned:.2f}, Test Acc: {acc_test_svm_tuned:.2f}")

print("\nConfusion Matrix (Test):", confusion_matrix(y_test, y_svm_test_pred))
print("\nClassification Report (Test):", classification_report(y_test, y_svm_test_pred))

In [ ]:
#Tuned Random Forest model (with real cross-validation via GridSearchCV)
param_grid_rf = {'n_estimators': [100, 200], 'max_depth': [None, 5, 10]}
grid_rf = GridSearchCV(RandomForestClassifier(random_state=42), param_grid_rf, cv=5, scoring='accuracy')
grid_rf.fit(X_train, y_train)

print("Best params:", grid_rf.best_params_)
print("Best CV accuracy:", grid_rf.best_score_)

best_rf = grid_rf.best_estimator_
y_rf_train_pred = best_rf.predict(X_train)
y_rf_test_pred = best_rf.predict(X_test)

acc_train_rf_tuned = accuracy_score(y_train, y_rf_train_pred)
acc_test_rf_tuned = accuracy_score(y_test, y_rf_test_pred)
print(f"Tuned RF - Train Acc: {acc_train_rf_tuned:.2f}, Test Acc: {acc_test_rf_tuned:.2f}")

print("\nConfusion Matrix (Test):", confusion_matrix(y_test, y_rf_test_pred))
print("\nClassification Report (Test):", classification_report(y_test, y_rf_test_pred))

In [ ]:
#Tuned Decision Tree model (with real cross-validation via GridSearchCV)
param_grid_dt = {'max_depth': [None, 5, 10, 20], 'criterion': ['gini', 'entropy']}
grid_dt = GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid_dt, cv=5, scoring='accuracy')
grid_dt.fit(X_train, y_train)

print("Best params:", grid_dt.best_params_)
print("Best CV accuracy:", grid_dt.best_score_)

best_dt = grid_dt.best_estimator_
y_dt_train_pred = best_dt.predict(X_train)
y_dt_test_pred = best_dt.predict(X_test)

acc_train_dt_tuned = accuracy_score(y_train, y_dt_train_pred)
acc_test_dt_tuned = accuracy_score(y_test, y_dt_test_pred)
print(f"Tuned DT - Train Acc: {acc_train_dt_tuned:.2f}, Test Acc: {acc_test_dt_tuned:.2f}")

print("\nConfusion Matrix (Test):", confusion_matrix(y_test, y_dt_test_pred))
print("\nClassification Report (Test):", classification_report(y_test, y_dt_test_pred))

In [ ]:
# Comparison table AFTER tuning, computed from actual tuned model predictions
tuned_preds = {
    'Logistic Regression (tuned)': (y_lr_train_pred, y_lr_test_pred),
    'KNN (tuned)': (y_knn_train_pred, y_knn_test_pred),
    'SVM (tuned)': (y_svm_train_pred, y_svm_test_pred),
    'Random Forest (tuned)': (y_rf_train_pred, y_rf_test_pred),
    'Decision Tree (tuned)': (y_dt_train_pred, y_dt_test_pred),
}

rows = []
for name, (pred_train, pred_test) in tuned_preds.items():
    rows.append({
        'Model': name,
        'Train Accuracy': accuracy_score(y_train, pred_train),
        'Test Accuracy': accuracy_score(y_test, pred_test),
        'Train F1 (-1)': f1_score(y_train, pred_train, pos_label=-1),
        'Train F1 (1)': f1_score(y_train, pred_train, pos_label=1),
        'Test F1 (-1)': f1_score(y_test, pred_test, pos_label=-1),
        'Test F1 (1)': f1_score(y_test, pred_test, pos_label=1),
    })

df_results_tuned = pd.DataFrame(rows)
print(df_results_tuned)

Stage 3:
Applying Deep Learing FFNN, CNN, Encoder - Decoder

In [ ]:
#Applying FFNN
# Convert Y from -1/1 to 0/1

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import StandardScaler


import numpy as np
y_train_enc = np.where(y_train == -1, 0, 1)
y_test_enc = np.where(y_test == -1, 0, 1)


model = Sequential([
    Dense(128, input_dim=X_train_scaled.shape[1], activation='relu'),
    Dropout(0.4),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])

# Compile model
model.compile(optimizer=Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train
history = model.fit(X_train_scaled, y_train_enc,
                    validation_data=(X_test_scaled, y_test_enc),
                    epochs=50, batch_size=32, verbose=1)

# Evaluate
loss, acc = model.evaluate(X_test_scaled, y_test_enc)
print(f"Test Accuracy: {acc*100:.2f}%")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

Epoch 1/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7594 - loss: 0.4753 - val_accuracy: 0.9295 - val_loss: 0.1834
Epoch 2/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9255 - loss: 0.2031 - val_accuracy: 0.9334 - val_loss: 0.1657
Epoch 3/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9365 - loss: 0.1679 - val_accuracy: 0.9361 - val_loss: 0.1527
Epoch 4/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9340 - loss: 0.1618 - val_accuracy: 0.9394 - val_loss: 0.1450
Epoch 5/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9386 - loss: 0.1546 - val_accuracy: 0.9445 - val_loss: 0.1360
Epoch 6/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9430 - loss: 0.1421 - val_accuracy: 0.9448 - val_loss: 0.1301
Epoch 7/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9393 - loss: 0.1405 - val_accuracy: 0.9436 - val_loss: 0.1255
Epoch 8/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9483 - loss: 0.1267 - val_accuracy: 0.9484 - val_loss: 0.1186
Epoch 9/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9477 - loss: 0.1247 - val_accuracy: 0.9509 - val_loss: 0.1147
Epoch 10/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9522 - loss: 0.1155 - val_accuracy: 0.9542 - val_loss: 0.1130
Epoch 11/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9550 - loss: 0.1107 - val_accuracy: 0.9530 - val_loss: 0.1095
Epoch 12/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9575 - loss: 0.1068 - val_accuracy: 0.9572 - val_loss: 0.1073
Epoch 13/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9518 - loss: 0.1153 - val_accuracy: 0.9593 - val_loss: 0.1038
Epoch 14/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9549 - loss: 0.1120 - val_accuracy: 0.9569 - val_loss: 0.1019
Epoch 15/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9510 - loss: 0.1106 - val_accuracy: 0.9602 - val_loss: 0.0999
Epoch 16/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9554 - loss: 0.1001 - val_accuracy: 0.9581 - val_loss: 0.0994
Epoch 17/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9586 - loss: 0.0898 - val_accuracy: 0.9626 - val_loss: 0.0950
Epoch 18/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9586 - loss: 0.0980 - val_accuracy: 0.9620 - val_loss: 0.0966
Epoch 19/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9584 - loss: 0.0979 - val_accuracy: 0.9620 - val_loss: 0.0972
Epoch 20/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9574 - loss: 0.0996 - val_accuracy: 0.9611 - val_loss: 0.0935
Epoch 21/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9577 - loss: 0.0923 - val_accuracy: 0.9614 - val_loss: 0.0914
Epoch 22/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9608 - loss: 0.0922 - val_accuracy: 0.9641 - val_loss: 0.0891
Epoch 23/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9618 - loss: 0.0884 - val_accuracy: 0.9629 - val_loss: 0.0929
Epoch 24/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9580 - loss: 0.0919 - val_accuracy: 0.9626 - val_loss: 0.0903
Epoch 25/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9689 - loss: 0.0726 - val_accuracy: 0.9635 - val_loss: 0.0869
Epoch 26/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9661 - loss: 0.0832 - val_accuracy: 0.9641 - val_loss: 0.0864
Epoch 27/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9625 - loss: 0.0838 - val_accuracy: 0.9650 - val_loss: 0.0836
Epoch 28/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9698 - loss: 0.0797 - val_accuracy: 0.9650 - val_loss: 0.0852
Epoch 29/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9667 - loss: 0.0778 - val_accuracy: 0.9644 - val_loss: 0.0839
Epoch 30/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9644 - loss: 0.0798 - val_accuracy: 0.9653 - val_loss: 0.0838
Epoch 31/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9632 - loss: 0.0781 - val_accuracy: 0.9644 - val_loss: 0.0854
Epoch 32/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9705 - loss: 0.0717 - val_accuracy: 0.9650 - val_loss: 0.0901
Epoch 33/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9696 - loss: 0.0726 - val_accuracy: 0.9659 - val_loss: 0.0872
Epoch 34/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9699 - loss: 0.0737 - val_accuracy: 0.9671 - val_loss: 0.0847
Epoch 35/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9686 - loss: 0.0690 - val_accuracy: 0.9659 - val_loss: 0.0842
Epoch 36/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9689 - loss: 0.0724 - val_accuracy: 0.9668 - val_loss: 0.0837
Epoch 37/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9699 - loss: 0.0709 - val_accuracy: 0.9659 - val_loss: 0.0855
Epoch 38/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9763 - loss: 0.0639 - val_accuracy: 0.9647 - val_loss: 0.0827
Epoch 39/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9701 - loss: 0.0670 - val_accuracy: 0.9665 - val_loss: 0.0845
Epoch 40/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9707 - loss: 0.0671 - val_accuracy: 0.9638 - val_loss: 0.0818
Epoch 41/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9725 - loss: 0.0699 - val_accuracy: 0.9665 - val_loss: 0.0802
Epoch 42/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9721 - loss: 0.0699 - val_accuracy: 0.9665 - val_loss: 0.0829
Epoch 43/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9704 - loss: 0.0653 - val_accuracy: 0.9653 - val_loss: 0.0867
Epoch 44/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9710 - loss: 0.0706 - val_accuracy: 0.9650 - val_loss: 0.0812
Epoch 45/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9709 - loss: 0.0645 - val_accuracy: 0.9659 - val_loss: 0.0806
Epoch 46/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9723 - loss: 0.0680 - val_accuracy: 0.9671 - val_loss: 0.0833
Epoch 47/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9738 - loss: 0.0645 - val_accuracy: 0.9671 - val_loss: 0.0834
Epoch 48/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9724 - loss: 0.0624 - val_accuracy: 0.9647 - val_loss: 0.0830
Epoch 49/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9752 - loss: 0.0614 - val_accuracy: 0.9662 - val_loss: 0.0833
Epoch 50/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9690 - loss: 0.0655 - val_accuracy: 0.9668 - val_loss: 0.0866
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9656 - loss: 0.0912
Test Accuracy: 96.68%

In [ ]:
#APPLYING
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, Flatten, Dense, Dropout

# Reshape for 1D CNN
X_train_cnn = X_train_scaled.reshape((X_train_scaled.shape[0], X_train_scaled.shape[1], 1))
X_test_cnn = X_test_scaled.reshape((X_test_scaled.shape[0], X_test_scaled.shape[1], 1))

cnn_model = Sequential([
    Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train_scaled.shape[1], 1)),
    Dropout(0.3),
    Conv1D(32, kernel_size=3, activation='relu'),
    Flatten(),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
cnn_model.fit(X_train_cnn, y_train_enc,
              validation_data=(X_test_cnn, y_test_enc),
              epochs=50, batch_size=32, verbose=1)

loss, acc = cnn_model.evaluate(X_test_cnn, y_test_enc)
print(f"CNN Test Accuracy: {acc*100:.2f}%")

Epoch 1/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8443 - loss: 0.3469 - val_accuracy: 0.9331 - val_loss: 0.1692
Epoch 2/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9306 - loss: 0.1776 - val_accuracy: 0.9279 - val_loss: 0.1628
Epoch 3/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9336 - loss: 0.1600 - val_accuracy: 0.9400 - val_loss: 0.1418
Epoch 4/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9413 - loss: 0.1423 - val_accuracy: 0.9385 - val_loss: 0.1387
Epoch 5/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9472 - loss: 0.1351 - val_accuracy: 0.9412 - val_loss: 0.1274
Epoch 6/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9403 - loss: 0.1363 - val_accuracy: 0.9497 - val_loss: 0.1164
Epoch 7/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9477 - loss: 0.1214 - val_accuracy: 0.9527 - val_loss: 0.1219
Epoch 8/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9525 - loss: 0.1152 - val_accuracy: 0.9509 - val_loss: 0.1085
Epoch 9/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9549 - loss: 0.1118 - val_accuracy: 0.9503 - val_loss: 0.1078
Epoch 10/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9553 - loss: 0.1130 - val_accuracy: 0.9509 - val_loss: 0.1088
Epoch 11/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9601 - loss: 0.0990 - val_accuracy: 0.9584 - val_loss: 0.1011
Epoch 12/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9597 - loss: 0.0956 - val_accuracy: 0.9545 - val_loss: 0.0973
Epoch 13/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9591 - loss: 0.0961 - val_accuracy: 0.9593 - val_loss: 0.0945
Epoch 14/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9611 - loss: 0.0923 - val_accuracy: 0.9578 - val_loss: 0.0975
Epoch 15/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9641 - loss: 0.0871 - val_accuracy: 0.9620 - val_loss: 0.0905
Epoch 16/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9645 - loss: 0.0826 - val_accuracy: 0.9599 - val_loss: 0.0897
Epoch 17/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9640 - loss: 0.0857 - val_accuracy: 0.9578 - val_loss: 0.0919
Epoch 18/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9625 - loss: 0.0870 - val_accuracy: 0.9587 - val_loss: 0.0911
Epoch 19/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9634 - loss: 0.0855 - val_accuracy: 0.9626 - val_loss: 0.0900
Epoch 20/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9661 - loss: 0.0831 - val_accuracy: 0.9626 - val_loss: 0.0853
Epoch 21/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9663 - loss: 0.0842 - val_accuracy: 0.9623 - val_loss: 0.0878
Epoch 22/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9640 - loss: 0.0823 - val_accuracy: 0.9641 - val_loss: 0.0850
Epoch 23/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9717 - loss: 0.0752 - val_accuracy: 0.9641 - val_loss: 0.0835
Epoch 24/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9682 - loss: 0.0779 - val_accuracy: 0.9590 - val_loss: 0.0881
Epoch 25/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9679 - loss: 0.0742 - val_accuracy: 0.9626 - val_loss: 0.0870
Epoch 26/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9663 - loss: 0.0693 - val_accuracy: 0.9632 - val_loss: 0.0831
Epoch 27/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9668 - loss: 0.0753 - val_accuracy: 0.9650 - val_loss: 0.0918
Epoch 28/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9701 - loss: 0.0690 - val_accuracy: 0.9623 - val_loss: 0.0897
Epoch 29/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9725 - loss: 0.0671 - val_accuracy: 0.9650 - val_loss: 0.0835
Epoch 30/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9722 - loss: 0.0633 - val_accuracy: 0.9629 - val_loss: 0.0875
Epoch 31/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9706 - loss: 0.0691 - val_accuracy: 0.9668 - val_loss: 0.0844
Epoch 32/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9704 - loss: 0.0641 - val_accuracy: 0.9650 - val_loss: 0.0866
Epoch 33/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9729 - loss: 0.0650 - val_accuracy: 0.9623 - val_loss: 0.0925
Epoch 34/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9707 - loss: 0.0602 - val_accuracy: 0.9653 - val_loss: 0.0893
Epoch 35/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9722 - loss: 0.0591 - val_accuracy: 0.9650 - val_loss: 0.0840
Epoch 36/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9745 - loss: 0.0607 - val_accuracy: 0.9632 - val_loss: 0.0867
Epoch 37/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9712 - loss: 0.0609 - val_accuracy: 0.9650 - val_loss: 0.0876
Epoch 38/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9666 - loss: 0.0681 - val_accuracy: 0.9674 - val_loss: 0.0921
Epoch 39/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9749 - loss: 0.0588 - val_accuracy: 0.9665 - val_loss: 0.0858
Epoch 40/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9724 - loss: 0.0611 - val_accuracy: 0.9680 - val_loss: 0.0892
Epoch 41/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9713 - loss: 0.0626 - val_accuracy: 0.9677 - val_loss: 0.0855
Epoch 42/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9755 - loss: 0.0553 - val_accuracy: 0.9662 - val_loss: 0.0894
Epoch 43/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9745 - loss: 0.0550 - val_accuracy: 0.9702 - val_loss: 0.0880
Epoch 44/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9737 - loss: 0.0568 - val_accuracy: 0.9665 - val_loss: 0.0875
Epoch 45/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9724 - loss: 0.0540 - val_accuracy: 0.9659 - val_loss: 0.0916
Epoch 46/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9751 - loss: 0.0570 - val_accuracy: 0.9677 - val_loss: 0.0990
Epoch 47/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9764 - loss: 0.0543 - val_accuracy: 0.9659 - val_loss: 0.0995
Epoch 48/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9697 - loss: 0.0644 - val_accuracy: 0.9683 - val_loss: 0.0884
Epoch 49/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9772 - loss: 0.0491 - val_accuracy: 0.9689 - val_loss: 0.0906
Epoch 50/50
242/242 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9744 - loss: 0.0576 - val_accuracy: 0.9696 - val_loss: 0.0894
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9700 - loss: 0.0904
CNN Test Accuracy: 96.96%

Trying Encoders and Decoders

In [ ]:
import torch
from torch import nn, optim
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# Convert to float32 tensors
X_train_t = torch.tensor(X_train.values, dtype=torch.float32)
y_train_t = torch.tensor(y_train.values, dtype=torch.float32)

X_test_t = torch.tensor(X_test.values, dtype=torch.float32)
y_test_t = torch.tensor(y_test.values, dtype=torch.float32)

# Create TensorDataset
train_dataset = TensorDataset(X_train_t, y_train_t)
test_dataset = TensorDataset(X_test_t, y_test_t)

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [ ]:
import torch
from torch import nn
input_size = X_train.shape[1]
class AE(nn.Module):
    def __init__(self,input_dim):
        super(AE, self).__init__()

        # Encoder
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 16),   # bottleneck (latent space)
        )

        # Decoder
        self.decoder = nn.Sequential(
            nn.Linear(16, 32),
            nn.ReLU(),
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, input_dim),
            nn.Sigmoid()        # outputs reconstructed features
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return decoded
X_train_t = torch.tensor(X_train.values, dtype=torch.float32)
X_test_t  = torch.tensor(X_test.values, dtype=torch.float32)

model = AE(input_dim=input_size)

train_loader = DataLoader(X_train_t, batch_size=32, shuffle=True)

In [ ]:
input_size = X_train.shape[1]   # 31 features

model = AE(input_dim=input_size)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(100):
    for batch in train_loader:
        preds = model(batch)
        loss = criterion(preds, batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}")

Epoch 1: Loss = 1320577.3750
Epoch 2: Loss = 1310363.7500
Epoch 3: Loss = 1563759.1250
Epoch 4: Loss = 1478827.6250
Epoch 5: Loss = 1422361.3750
Epoch 6: Loss = 1376132.0000
Epoch 7: Loss = 1164563.3750
Epoch 8: Loss = 1272598.5000
Epoch 9: Loss = 1377823.0000
Epoch 10: Loss = 1280910.2500
Epoch 11: Loss = 1327798.5000
Epoch 12: Loss = 1198445.1250
Epoch 13: Loss = 1285782.2500
Epoch 14: Loss = 1030694.3750
Epoch 15: Loss = 1787981.5000
Epoch 16: Loss = 1336679.7500
Epoch 17: Loss = 1644355.8750
Epoch 18: Loss = 1439678.8750
Epoch 19: Loss = 1189789.1250
Epoch 20: Loss = 1424964.5000
Epoch 21: Loss = 1356782.0000
Epoch 22: Loss = 1508579.6250
Epoch 23: Loss = 1275269.1250
Epoch 24: Loss = 1578932.0000
Epoch 25: Loss = 1451785.2500
Epoch 26: Loss = 1221831.3750
Epoch 27: Loss = 1051955.3750
Epoch 28: Loss = 1497113.6250
Epoch 29: Loss = 1488621.1250
Epoch 30: Loss = 804350.1875
Epoch 31: Loss = 1091739.6250
Epoch 32: Loss = 2120683.2500
Epoch 33: Loss = 1506840.5000
Epoch 34: Loss = 1441958.6250
Epoch 35: Loss = 1397458.7500
Epoch 36: Loss = 1141390.0000
Epoch 37: Loss = 1274852.5000
Epoch 38: Loss = 1519207.8750
Epoch 39: Loss = 1179826.6250
Epoch 40: Loss = 1034986.8750
Epoch 41: Loss = 1179221.2500
Epoch 42: Loss = 1075148.5000
Epoch 43: Loss = 1611321.1250
Epoch 44: Loss = 1409159.1250
Epoch 45: Loss = 905708.2500
Epoch 46: Loss = 1403144.3750
Epoch 47: Loss = 1434101.2500
Epoch 48: Loss = 909917.6250
Epoch 49: Loss = 1522384.7500
Epoch 50: Loss = 1422393.5000
Epoch 51: Loss = 1187920.5000
Epoch 52: Loss = 1158452.6250
Epoch 53: Loss = 1822823.7500
Epoch 54: Loss = 1792489.2500
Epoch 55: Loss = 1194326.2500
Epoch 56: Loss = 1372798.8750
Epoch 57: Loss = 1256709.6250
Epoch 58: Loss = 1404283.7500
Epoch 59: Loss = 1574785.3750
Epoch 60: Loss = 1638866.8750
Epoch 61: Loss = 1579378.2500
Epoch 62: Loss = 1453894.8750
Epoch 63: Loss = 1310961.8750
Epoch 64: Loss = 1413893.2500
Epoch 65: Loss = 1305193.8750
Epoch 66: Loss = 1280288.5000
Epoch 67: Loss = 1729256.8750
Epoch 68: Loss = 1081408.3750
Epoch 69: Loss = 886257.6250
Epoch 70: Loss = 1410056.1250
Epoch 71: Loss = 688527.8750
Epoch 72: Loss = 1442499.7500
Epoch 73: Loss = 1163957.2500
Epoch 74: Loss = 1370869.6250
Epoch 75: Loss = 842308.4375
Epoch 76: Loss = 1452310.2500
Epoch 77: Loss = 1320744.1250
Epoch 78: Loss = 907026.5000
Epoch 79: Loss = 1690096.2500
Epoch 80: Loss = 985242.1875
Epoch 81: Loss = 1264190.6250
Epoch 82: Loss = 1232866.2500
Epoch 83: Loss = 1469241.2500
Epoch 84: Loss = 1361401.3750
Epoch 85: Loss = 1929654.8750
Epoch 86: Loss = 1642902.2500
Epoch 87: Loss = 1709310.1250
Epoch 88: Loss = 1186947.5000
Epoch 89: Loss = 1063556.8750
Epoch 90: Loss = 995058.8125
Epoch 91: Loss = 1030394.0625
Epoch 92: Loss = 1493104.1250
Epoch 93: Loss = 1144817.6250
Epoch 94: Loss = 828781.0625
Epoch 95: Loss = 1618343.6250
Epoch 96: Loss = 1302037.5000
Epoch 97: Loss = 1280640.5000
Epoch 98: Loss = 1350611.8750
Epoch 99: Loss = 1371031.8750
Epoch 100: Loss = 1318152.8750

In [ ]:
with torch.no_grad():
    encoded_train = model.encoder(X_train_t)
    encoded_test  = model.encoder(X_test_t)

Xtr = encoded_train.cpu().numpy()
Xte = encoded_test.cpu().numpy()

ytr = y_train.values
yte = y_test.values

#Scaling the data for LR
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
Xtr_scaled = scaler.fit_transform(Xtr)
Xte_scaled = scaler.transform(Xte)

In [ ]:
#Applying logistical Regression with encoded data
model_log_reg = LogisticRegression(max_iter=1000)
model_log_reg.fit(Xtr_scaled, ytr) #Logictical regressions need scaling

model_log_reg_pred_train = model_log_reg.predict(Xtr_scaled) #train
model_log_reg_pred_test = model_log_reg.predict(Xte_scaled) #test

# Estimating the accuracy for training data
acc_train_log_reg = accuracy_score(ytr, model_log_reg_pred_train)
print("accuracy score (training data): %.2f" % acc_train_log_reg)

# Estimating the accuracy for test data
acc_test_log_reg = accuracy_score(yte, model_log_reg_pred_test)
print("accuracy score (test data): %.2f" % acc_test_log_reg)

#for showing accuracy,
lreg_results = pd.DataFrame({
  'model': ['lr'],
  'train_acc': [acc_train_log_reg],
  'test_acc': [acc_test_log_reg]
})

accuracy score (training data): 0.90
accuracy score (test data): 0.90

In [ ]:
# Applying KNN model (using encoded features)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

N_NEAREST_NEIGHOR_PARAM = 10
model_knn = KNeighborsClassifier(n_neighbors=N_NEAREST_NEIGHOR_PARAM)

# Fit on encoded + scaled training data
model_knn.fit(Xtr_scaled, ytr)

# Predictions
model_knn_pred_train = model_knn.predict(Xtr_scaled)
model_knn_pred_test = model_knn.predict(Xte_scaled)

# Accuracy
acc_train_knn = accuracy_score(ytr, model_knn_pred_train)
acc_test_knn = accuracy_score(yte, model_knn_pred_test)

print("KNN accuracy score (training data): %.2f" % acc_train_knn)
print("KNN accuracy score (test data): %.2f" % acc_test_knn)

# Save result
knn_results = pd.DataFrame({
    'model': ['knn_encoded'],
    'train_acc': [acc_train_knn],
    'test_acc': [acc_test_knn]
})

KNN accuracy score (training data): 0.92
KNN accuracy score (test data): 0.91

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

model_svm = SVC()

# Train on encoded + scaled data
model_svm.fit(Xtr_scaled, ytr)

# Predictions
model_svm_pred_train = model_svm.predict(Xtr_scaled)
model_svm_pred_test  = model_svm.predict(Xte_scaled)

# Accuracy
acc_train_svm = accuracy_score(ytr, model_svm_pred_train)
acc_test_svm  = accuracy_score(yte, model_svm_pred_test)

print("SVM accuracy (train): %.2f" % acc_train_svm)
print("SVM accuracy (test): %.2f" % acc_test_svm)

svm_results = pd.DataFrame({
    'model': ['svm_encoded'],
    'train_acc': [acc_train_svm],
    'test_acc': [acc_test_svm]
})

SVM accuracy (train): 0.91
SVM accuracy (test): 0.91

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

# Fit on encoded data
model_rf.fit(Xtr_scaled, ytr)

# Predictions
model_rf_pred_train = model_rf.predict(Xtr_scaled)
model_rf_pred_test  = model_rf.predict(Xte_scaled)

# Accuracy
acc_train_rf = accuracy_score(ytr, model_rf_pred_train)
acc_test_rf  = accuracy_score(yte, model_rf_pred_test)

print("RF accuracy (train): %.2f" % acc_train_rf)
print("RF accuracy (test): %.2f" % acc_test_rf)

rf_results = pd.DataFrame({
    'model': ['rf_encoded'],
    'train_acc': [acc_train_rf],
    'test_acc': [acc_test_rf]
})

RF accuracy (train): 0.91
RF accuracy (test): 0.90

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(random_state=42)

# Fit on encoded data
model_dt.fit(Xtr_scaled, ytr)

# Predictions
model_dt_pred_train = model_dt.predict(Xtr_scaled)
model_dt_pred_test  = model_dt.predict(Xte_scaled)

# Accuracy
acc_train_dt = accuracy_score(ytr, model_dt_pred_train)
acc_test_dt  = accuracy_score(yte, model_dt_pred_test)

print("DT accuracy (train): %.2f" % acc_train_dt)
print("DT accuracy (test): %.2f" % acc_test_dt)

dt_results = pd.DataFrame({
    'model': ['dt_encoded'],
    'train_acc': [acc_train_dt],
    'test_acc': [acc_test_dt]
})

DT accuracy (train): 1.00
DT accuracy (test): 0.87